bimanual_planning:
    num_agents_ee: 10
    num_agents_body: 1
    k_attr: 4.0
    k_circ: 0.10
    k_repel: 0.015
    k_damp: 3.0
    k_manip: 0.0
    k_repel_body: 0.02
    k_goal_dist: 100.0
    k_path_len: 10.0
    k_safe_dist: 0.001
    k_workspace: 5
    desired_ws_limits: [0.8, 0.35, 0.6, -0.6, 0.8, 0.2]
    max_prediction_steps: 1500
    approach_dist: 0.25
    detect_shell_rad: 0.35
    prediction_freq_multiple: 1
    frequency_ros: 100
    velocity: 0.3
    reflex_tau_max: [100, 100, 100, 80, 80, 40, 40]
    reflex_F_max: [100, 100, 100, 30, 30, 30]
    detect_F_min: [-10, -10, -10, -3, -3, -3]
    detect_F_max: [10, 10, 10, 3, 3, 3]
    gesture_F_th: 10
    gripper_width: 0.035
    switching: true
    open_loop: true
    visualize_commanded_path: true
    visualize_predicted_paths: true
    force_feedback: 0.0
    force_offset: [0.0, 0.0, 10.0]
    force_dead_zone: 10.0
    low_level_gain: 1.5
    robot_type: dual_panda
    q_goal_left: [1.0393815454851116, -1.4615167648164527, -1.8893381498570507, -1.3693482541530988, -1.385642144316263, 2.17184966263218, -1.8525699153576969]
    q_goal_right: [-0.3917776697100254, 0.28093264867130074, -0.0119228161701231, -1.3869026028984472, 0.7112445678777165, 1.7680162143707272, -0.33459241296516523]
    obstacles:
      - pos: [0.91, -0.01, 0.25]
        radius: 0.125
        vel: [0.0, 0.0, 0.0]
      - pos: [0.91, -0.01, 0.4]
        radius: 0.125
        vel: [0.0, 0.0, 0.0]
      - pos: [1.15, 0.2, 0.4]
        radius: 0.1
        vel: [-0.07, 0.0, 0.0]
      # Repulsive obstacle for self collision avoidance
      - pos: [0.0, 0.0, 0.50]
        radius: 0.3
        vel: [0.0, 0.0, 0.0]
    controller_list:
      - type: relative_pose
        gain: 0.005
      - type: ee_tilt
        gain: 0.1
      - type: joint_limit_avoidance
        gain: 0.9
      - type: absolute_position
        gain: 1.0
      - type: whole_body_avoidance
        gain: 0.0
    goals:
      - type: key
        message: "Press any key to start moving to initial position."
      - type: error_recovery
      - type: release
      - type: goto
        event: "moving to initial position"
      - type: key
        message: "Press start planning."
      - type: plan
        pos: [0.75, 0.45, 0.45]
        end_condition: reached
